movieproject/movieapp/urls.py
from django.urls import path
from .import views

app_name='movieapp'
urlpatterns = [
    path('', views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add,name='add'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
     urlpatterns+=static(settings.STATIC_URL,
                         document_root=settings.STATIC_ROOT)
     urlpatterns+=static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
   name=models.CharField(max_length=250)
   desc=models.TextField()
   year=models.IntegerField()
   img=models.ImageField(upload_to='gallery')

   def __str__(self):
          return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import  movie

class movieform(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movie
from .forms import movieform

# Create your views here.
def index(request):
     movie1 = movie.objects.all()
     context={
            'movie_list':movie1
        }
     return render(request,'index.html',context)

def detail(request,movie_id):
    movie2=movie.objects.get(id=movie_id)
    return render(request,'detail.html' ,{'movie':movie2})

def add(request):
    if request.method=='POST':
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        year=request.POST.get('year')
        img=request.FILES['img']
        movie1=movie(name=name,desc=desc,year=year,img=img)
        movie1.save()
        return redirect('/')
    return render(request,'add.html')

def update(request,id):
    movie1=movie.objects.get(id=id)
    form=movieform(request.POST or None,request.FILES,instance=movie1)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie1})

def delete(request,id):
    if request.method=='POST':
        movie1=movie.objects.get(id=id)
        movie1.delete()
        return redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        form{
        text-align:center;
        }
    </style>
</head>
<body>
{% extends 'base.html' %}
{% block body %}

<br><form method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <input type="text" name="name" placeholder="Enter movie name"><br><br>
        <input type="text" name="desc" placeholder="Enter movie description"><br><br>
        <input type="text" name="year" placeholder="Enter movie year"><br><br>
        <input type="file" name="img"><br><br>
        <input type="submit">

</form>
{% endblock %}
</body>
</html>

movieproject/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <link rel="stylesheet" href= 'style.css' >
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online  Movie Store
  </a>
 <a class="btn btn-warning" href="add/">Add Movie</a>

</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/delete.html
<form method="post">
    {% csrf_token %}
    Are you want to delete this movie?
   <br><input type="submit">
</form>

movieproject/templates/detail.html
{% extends 'base.html'%}
{% block body %}
<div class="container">
    <div class="row">
    <div class="col-md-6">
      <img src="{{movie.img.url}}" width="400" height="400">
    </div>
    <div class="col-md-6">
        <h4>{{movie.name}}</h4>
        <h6>{{movie.desc}}</h6>
        <h5>{{movie.year}}</h5>
        <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">Update</a>
        <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">Delete</a>
    </div>
</div>
    </div>

{% endblock %}

movieproject/templates/edit.html
<form style="align:center" method="post" enctype="multipart/form-data">
  <h4>Update Details</h4>
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>

movieproject/templates/index.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        {% for i in movie_list %}

        <div class="col-md-4">
           <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="250">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <p class="card-text">{{i.desc}}</p>
    <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary" >Go</a>
  </div>
</div>
        </div>
        {% endfor %}

    </div>
</div>
<!--{{i.name}}&#45;&#45;&ndash;&gt;{{i.desc}}&#45;&#45;&ndash;&gt;{{i.year}}<br>-->
<!--{{i.name}}-->
<!--<a href="movie/{{i.id}}">{{i.name}}</a>-->

{% endblock %}